language: php
php:
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cp .env.example .env
  - phpenv config-rm xdebug.ini
  - sleep 3
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose
